name: discord-hs
version: 0.1.0.0
license: MIT
license-file: LICENSE
maintainer: Connor James
github: cnr/discord-hs

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
dependencies:
  - base ^>=4.12.0.0

default-extensions:
  - DataKinds
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NumericUnderscores
  - OverloadedStrings
  - ScopedTypeVariables

library:
  source-dirs: src
  exposed-modules:
    - Discord.Client
    - Discord.Gateway
    - Discord.Main
    - Discord.Rest
    - Discord.Types
  dependencies:
    - aeson
    - bytestring
    - containers
    - http-client
    - http-types
    - lens
    - mtl
    - network
    - req
    - text
    - unliftio
    - websockets
    - wuss
