name: discord-hs
version: 0.1.0.0
license: MIT
license-file: LICENSE
maintainer: Connor James
github: cnr/discord-hs

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

  - -O2
  - -flate-specialise
  - -fspecialise-aggressively

dependencies:
  - base ^>=4.12.0.0

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NumericUnderscores
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies

library:
  source-dirs: src
  exposed-modules:
    - Discord
    - Discord.Gateway
    - Discord.Main
    - Discord.Rest
    - Discord.Rest.Channel
    - Discord.Types
    - Discord.Types.Common
    - Discord.Types.Gateway
  dependencies:
    - aeson
    - bytestring
    - case-insensitive
    - containers
    - http-client
    - http-types
    - lens
    - mtl
    - network
    - polysemy ^>=1.0.0.0
    - req
    - stm-chans
    - text
    - time
    - unliftio
    - websockets
    - wuss
